name: Development build

on:
  pull_request:
    branches-ignore:
      - 'l10n_main'
    types: [opened, reopened]
  push:
    branches-ignore:
      - 'l10n_main'
  workflow_dispatch:

jobs:
  build:
    name: Development build
    strategy:
      matrix:
        include:
          - platform: 2
            platform_name: ios

    runs-on: macos-latest

    steps:
      # 1) Always checkout first
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout repository submodules
        run: git submodule update --init --recursive

      # 2) (Optional) Remove only build artifacts, not the entire working directory
      - name: Clean up old build artifacts
        run: |
          echo "Before cleanup:"
          ls -lah .
          # Remove only known build/output directories, not the entire repo
          rm -rf artifacts/ || true
          rm -rf build/ || true
          echo "After cleanup:"
          ls -lah .

      # 3) Grab the latest gl4es commit hash
      - name: Get gl4es latest commit hash
        id: gl4es-sha
        run: |
          sha=$(git ls-remote https://github.com/PojavLauncherTeam/gl4es-114-extra refs/heads/master | awk '{print $1}')
          echo "sha=$sha" >> "$GITHUB_OUTPUT"

      # 4) Cache gl4es (disabled by default; remove `if: ${{ false }}` to enable)
      - name: Cache gl4es
        uses: actions/cache@v3
        if: ${{ false }} # enable if you want to use a cached version instead of building from scratch
        id: gl4es-cache
        with:
          path: gl4es/libs
          key: gl4es-holy-ios-shared-2-${{ steps.gl4es-sha.outputs.sha }}

      # 5) Check out gl4es only if cache missed (disabled by default)
      - name: Get gl4es
        uses: actions/checkout@v3
        if: ${{ false && steps.gl4es-cache.outputs.cache-hit != 'true' }}
        with:
          repository: 'PojavLauncherTeam/gl4es-114-extra'
          path: 'gl4es'

      # 6) Build gl4es (disabled by default)
      - name: Build gl4es
        if: ${{ false && steps.gl4es-cache.outputs.cache-hit != 'true' }}
        continue-on-error: true
        run: |
          cd gl4es
          git config user.email "github-actions@users.noreply.github.com"
          git config user.name "github-actions"
          export PATH=/opt/procursus/bin:$PATH
          wget https://github.com/leetal/ios-cmake/raw/master/ios.toolchain.cmake
          cmake -B build -DCMAKE_TOOLCHAIN_FILE=ios.toolchain.cmake -DDEFAULT_ES=2 \
            -DNOX11=ON -DNOEGL=OFF -DSTATICLIB=OFF -DPLATFORM=OS64 \
            -DCMAKE_C_FLAGS=-Wno-error=implicit-function-declaration
          cmake --build build --config RelWithDebInfo --target GL
          cp -R lib/libGL.dylib ../Natives/resources/Frameworks/libgl4es_114.dylib

      # 7) Push updated gl4es back to the repo (disabled by default)
      - name: Push gl4es
        if: ${{ false && github.event_name != 'pull_request' && github.ref_name == 'main' && steps.gl4es-cache.outputs.cache-hit != 'true' }}
        continue-on-error: true
        run: |
          git add Natives/resources/Frameworks/libgl4es_114.dylib
          git commit -am "CI: Update gl4es"
          git push

      # 8) Build for the given matrix.platform_name
      - name: Build for ${{ matrix.platform_name }}
        run: |
          export PATH=/opt/homebrew/bin:$PATH
          export SLIMMED=1

          if [ "${{ matrix.platform_name }}" == "ios" ]; then
            # Build ipa and tipa for iOS
            gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }}
            gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }} TROLLSTORE_JIT_ENT=1
          elif [ "${{ matrix.platform_name }}" == "tvos" ]; then
            # Build tipa only for tvOS
            gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }} TROLLSTORE_JIT_ENT=1
          else
            # Build ipa only for everything else
            gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }}
          fi

      # 9) Upload the various artifacts
      - name: Upload regular ipa
        uses: actions/upload-artifact@v3
        with:
          name: org.angelauramc.amethyst-${{ matrix.platform_name }}.ipa
          path: artifacts/org.angelauramc.amethyst-*-${{ matrix.platform_name }}.ipa

      - name: Upload regular tipa
        uses: actions/upload-artifact@v3
        with:
          name: org.angelauramc.amethyst-${{ matrix.platform_name }}-trollstore.tipa
          path: artifacts/org.angelauramc.amethyst-*-${{ matrix.platform_name }}-trollstore.tipa

      - name: Upload slimmed ipa
        uses: actions/upload-artifact@v3
        with:
          name: org.angelauramc.amethyst.slimmed-${{ matrix.platform_name }}.ipa
          path: artifacts/org.angelauramc.amethyst.slimmed-*-${{ matrix.platform_name }}.ipa

      - name: Upload slimmed tipa
        uses: actions/upload-artifact@v3
        with:
          name: org.angelauramc.amethyst.slimmed-${{ matrix.platform_name }}-trollstore.tipa
          path: artifacts/org.angelauramc.amethyst.slimmed-*-${{ matrix.platform_name }}-trollstore.tipa

      - name: Upload AngelAuraAmethyst dSYM
        if: ${{ matrix.platform_name == 'ios' }}
        uses: actions/upload-artifact@v3
        with:
          name: AngelAuraAmethyst.dSYM
          path: artifacts/AngelAuraAmethyst.dSYM
